version : '3'
services:
  tomcat:
    image: tomcat
    ports:
      - "9527:8080"
    volumes:
      - /usr/local/tomcat/webapps:/usr/local/tomcat/webapps
    restart: always
    depends_on:
      - dm-ui
    container_name: dm_tomcat
  dm-ui:
    image: dm/dm-ui
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /usr/local/tomcat/webapps:/usr/local/tomcat/webapps
    container_name: dm-ui
    restart: always
